language: android
env:
  global:
  - MALLOC_ARENA_MAX=2
sudo: required
android:
  components:
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew :app:assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: etdqFuvdHmgyrSKecpNKz5p+C6lSMF7QbhvwW+iSJLu9nCVwF/05HwUxDC6qJNF6bzhZpmjlcpURDeshaoa40Ozngvnbm7N/4SCpBl0EkDCxMgMRgI8O+Q5zJJLAJBA8ppdEXYwG8h0xdHJSMv+SDuN/Vq2g+23wLzzh/ucneig=
  file: 'app/build/outputs/apk/app-debug.apk'
  skip_cleanup: true
  on:
    repo: easemob/kefu-android-demo
    tags: true
